printWidth: 120
tabWidth: 1
usetabs: true
semi: true
singleQuote: true
quoteProps: as-needed
trailingCommas: none
bracketSpacing: true
bracketSameLine: true
arrowParens: always
htmlWhitespaceSensitivity: css
singleAttributePerLine: true