name: Prettier

on:
  pull_requests:
    branches:
      - master
      
jobs:
    name: Prettier
    steps:
    - name: Prettier
      steps:
      - name: Install Prettier
        run: npm install prettier
      - name: Format Check
        run: npx prettier . --check --config config/.prettierrc.yaml